[package]
name = "rs-chardet"
version = "0.1.0"
authors = ["miguelsousa"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chardet = "0.2.4"